name: "🧩 Plugin/Provider request"
description: Ask us to add your plugin/provider to the list
title: "[PLUGIN/PROVIDER REQUEST] <title>"
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: "Name of your plugin/provider as it is used to install it"
      placeholder: "Example: strapi-plugin-json-schema"
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link
      description: "Please provide a link where we can find your plugin/provider, it can be `Github` or `NPM`"
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: "Tell us if your plugin/provider is either ready to use in v4 or unsupported. If it is in progress or you don't know, tell us anyway"
      options:
      - Unknown
      - Work In Progess
      - Ready
      - Unsupported
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: "Is this a `Plugin` or a `Provider`"
      options:
      - Plugin
      - Provider
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author
      description: "Even if you are not the author of this plugin/provider, please give us his Github name so we can contact it"
      placeholder: "Example: @Stun3R"